#  Developed by t.me/napaaextra
from pyrogram import Client, filters
from pyrogram.types import Message, InlineKeyboardMarkup, InlineKeyboardButton
from pyrogram.enums import ParseMode
from pyrogram.errors.pyromod import ListenerTimeout
from helper.helper_func import encode, get_message_id
import asyncio


MIGRATOR_BOT = "LelouchAMbot"


async def ask_for_message(client, user_id, prompt_text):
    """Ask for a message and listen for the response."""
    prompt_message = await client.send_message(user_id, prompt_text, parse_mode=ParseMode.HTML)
    try:
        response = await client.listen(
            chat_id=user_id,
            filters=(filters.forwarded | (filters.text & ~filters.forwarded)),
            timeout=60
        )
        await prompt_message.delete()
        return response
    except ListenerTimeout:
        await prompt_message.edit("<b>⏰ Timeout!</b> Please try the command again.")
        return None

def create_smart_link_message(migrator_link, direct_link, link_type="File"):
    """Create a formatted message for link sharing"""
    return (
        f"<b>✅ {link_type} ʟɪɴᴋ ɢᴇɴᴇʀᴀᴛᴇᴅ!</b>\n\n"
        f"<b>📤 ꜰᴏʀ ᴘᴜʙʟɪᴄ ᴄʜᴀɴɴᴇʟꜱ (ᴜꜱᴇ ᴛʜɪꜱ!):</b>\n"
        f"<code>{migrator_link}</code>\n\n"
        f"<blockquote><b>🔗 ᴀʟᴛᴇʀɴᴀᴛɪᴠᴇ ʟɪɴᴋ:</b>\n"
        f"<code>{direct_link}</code></blockquote>"
    )

def create_smart_buttons(migrator_link, direct_link):
    """Create smart button markup with migrator and direct links"""
    return InlineKeyboardMarkup([
        [InlineKeyboardButton("ʀᴇᴅɪʀᴇᴄᴛ ʙᴏᴛ ʟɪɴᴋ", url=migrator_link)],
        [InlineKeyboardButton("ᴄᴜʀʀᴇɴᴛ ʙᴏᴛ ʟɪɴᴋ", url=direct_link)]])


@Client.on_message(filters.private & filters.command('batch'))
async def batch(client: Client, message: Message):
    """Generate batch link for a range of messages."""
    
    if message.from_user.id not in client.admins:
        return await message.reply(client.reply_text)
    
    while True:
        first_message = await ask_for_message(
            client,
            message.from_user.id,
            "<b>📨 Forward the <u>First Message</u> from DB Channel</b>\n\n"
            "<i>You can also send the message link</i>"
        )
        if not first_message:
            return

        f_channel_id, f_msg_id = await get_message_id(client, first_message)
        if f_msg_id:
            break
        else:
            await first_message.reply(
                "❌ <b>Invalid Message</b>\n\n"
                "This message is not from a configured DB Channel. Please try again.",
                quote=True,
                parse_mode=ParseMode.HTML
            )

    while True:
        second_message = await ask_for_message(
            client,
            message.from_user.id,
            "<b>📨 Forward the <u>Last Message</u> from DB Channel</b>\n\n"
            "<i>You can also send the message link</i>"
        )
        if not second_message:
            return

        s_channel_id, s_msg_id = await get_message_id(client, second_message)
        if s_msg_id:
            break
        else:
            await second_message.reply(
                "❌ <b>Invalid Message</b>\n\n"
                "This message is not from a configured DB Channel. Please try again.",
                quote=True,
                parse_mode=ParseMode.HTML
            )

    if f_channel_id != s_channel_id:
        return await second_message.reply(
            "❌ <b>Error</b>\n\n"
            "Both messages must be from the same channel.",
            quote=True,
            parse_mode=ParseMode.HTML
        )
    
    
    string = f"batch_{f_channel_id}_{f_msg_id}_{s_msg_id}"
    base64_string = await encode(string)
    
    migrator_link = f"https://t.me/{MIGRATOR_BOT}?start={base64_string}"
    direct_link = f"https://t.me/{client.username}?start={base64_string}"
    
    response_text = create_smart_link_message(migrator_link, direct_link, "Batch")
    reply_markup = create_smart_buttons(migrator_link, direct_link)
    
    await second_message.reply_text(
        response_text,
        quote=True,
        reply_markup=reply_markup,
        parse_mode=ParseMode.HTML,
        disable_web_page_preview=True
    )
    
    client.LOGGER(__name__, client.name).info(
        f"Batch link generated by {message.from_user.id}: {f_msg_id}-{s_msg_id} from {f_channel_id}"
    )


@Client.on_message(filters.private & filters.command('genlink'))
async def link_generator(client: Client, message: Message):
    """Generate link for a single message."""
    
    if message.from_user.id not in client.admins:
        return await message.reply(client.reply_text)
    
    while True:
        channel_message = await ask_for_message(
            client,
            message.from_user.id,
            "<b>📨 Forward a message from DB Channel</b>\n\n"
            "<i>You can also send the message link</i>"
        )
        if not channel_message:
            return

        channel_id, msg_id = await get_message_id(client, channel_message)
        if msg_id:
            break
        else:
            await channel_message.reply(
                "❌ <b>Invalid Message</b>\n\n"
                "This message is not from a configured DB Channel. Please try again.",
                quote=True,
                parse_mode=ParseMode.HTML
            )


    base64_string = await encode(f"single_{channel_id}_{msg_id}")
    
    migrator_link = f"https://t.me/{MIGRATOR_BOT}?start={base64_string}"
    direct_link = f"https://t.me/{client.username}?start={base64_string}"
    
    response_text = create_smart_link_message(migrator_link, direct_link, "Single File")
    reply_markup = create_smart_buttons(migrator_link, direct_link)
    
    await channel_message.reply_text(
        response_text,
        quote=True,
        reply_markup=reply_markup,
        parse_mode=ParseMode.HTML,
        disable_web_page_preview=True
    )
    
    client.LOGGER(__name__, client.name).info(
        f"Single link generated by {message.from_user.id}: {msg_id} from {channel_id}"
    )


